-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost:8889
-- Generation Time: Feb 11, 2025 at 07:33 PM
-- Server version: 8.0.40
-- PHP Version: 8.3.14

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `film_database`
--

-- --------------------------------------------------------

--
-- Table structure for table `films`
--

CREATE TABLE `films` (
  `id` int NOT NULL,
  `titel` varchar(255) NOT NULL,
  `beschrijving` text,
  `prijs` int DEFAULT NULL,
  `afbeelding_url` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `films`
--

INSERT INTO `films` (`id`, `titel`, `beschrijving`, `prijs`, `afbeelding_url`) VALUES
(1, 'Macintosh Classic', 'The Macintosh Classic, released in 1990, was a compact and affordable personal computer from Apple. It was the successor to the original Macintosh and part of the Macintosh II series. Featuring a 9-inch monochrome CRT display and powered by the Motorola 68000 processor, it was designed to offer a more budget-friendly option for consumers who wanted to experience the Macintosh environment without the higher cost of previous models. The Classic came with 1MB of RAM (expandable to 4MB) and a 40MB hard drive, which provided a decent storage capacity for its time. Its simple design, characterized by a compact, all-in-one form factor, made it an attractive choice for home users and educational institutions. The Macintosh Classic marked a pivotal moment in Apple\'s efforts to make personal computing more accessible, despite the limited color display and lower processing power compared to its contemporaries.', 148, '/eindopdracht/images/macintoshclassic.jpg'),
(2, 'Imac G3', 'The iMac G3, introduced in 1998, was a revolutionary product that played a key role in revitalizing Apple’s brand and the personal computing industry. Designed by Jonathan Ive, it featured a striking, colorful, translucent plastic case that set it apart from the dull, boxy designs of other computers at the time. The iMac G3 was powered by an all-in-one design, combining the monitor and computer components into a single unit. It was equipped with an integrated 15-inch CRT display, a PowerPC G3 processor, and came with 32MB of RAM and a 4GB hard drive, offering a significant performance boost for the era. Notably, it was one of the first consumer computers to feature USB ports, a move that helped standardize the interface across devices. Available in a variety of vibrant colors, from Bondi Blue to Tangerine, the iMac G3 was not just a technological marvel but a statement piece in homes and offices. Its bold design and user-friendly features made it a significant cultural icon and helped cement Apple’s reputation for innovation and style in the personal computing space.', 233, 'images/imacg3.png\r\n'),
(3, 'Amiga 500', 'The Amiga 500, released in 1987 by Commodore, was a highly regarded personal computer that earned a reputation for its advanced graphics and sound capabilities, making it a popular choice among gamers, graphic designers, and multimedia enthusiasts. Powered by the Motorola 68000 processor, it featured 512KB of RAM (expandable to 9MB) and offered a unique multimedia experience with its custom graphics and audio chips, allowing for detailed visuals and high-quality sound—unmatched by many PCs of its time. The Amiga 500 came with the AmigaOS, a multitasking operating system that set it apart from other home computers, allowing users to run multiple applications simultaneously. Its 16-bit graphics and support for advanced color palettes made it ideal for video editing, animation, and gaming, establishing it as a key player in creative industries. With a built-in floppy disk drive and compatibility with a wide range of peripherals, the Amiga 500 was a versatile and forward-thinking machine. Though it never achieved mainstream success, its impact on the computer industry and its legacy among enthusiasts remains significant.', 256, '/eindopdracht/images/amiga500.png\r\n'),
(4, 'Ipod 1st gen', 'The original iPod, released in 2001, marked Apple’s entry into the portable music player market and became an iconic device in tech history. With its sleek white design, mechanical scroll wheel, and 5GB hard drive, it offered users a revolutionary way to store and play music on-the-go. It was one of the first devices to feature seamless integration with Apple\'s iTunes software, which allowed users to easily manage and transfer music to the device. Despite its initial price tag of $399, the iPod quickly gained popularity for its innovative interface and exceptional user experience. Over time, the iPod evolved into several models and became a major factor in Apple\'s success, helping to pave the way for future product innovations such as the iPhone.', 122, '/eindopdracht/images/ipod1g.png'),
(5, 'Macintosh Plus', 'The Macintosh Plus, released in 1986, was a significant upgrade to the original Macintosh and became one of the most successful early models in Apple’s history. Featuring a 9-inch monochrome display and powered by the Motorola 68000 processor, it was one of the first Macs to support 1MB of RAM (expandable to 4MB) and offered users the ability to connect external storage devices such as hard drives and printers via its SCSI port. The Macintosh Plus was known for its reliability, ease of use, and enhanced performance, and it was compatible with a wide range of third-party software, making it a favorite in educational and professional settings. The introduction of the Macintosh Plus also saw the arrival of the System 3 operating system, which improved the overall user experience.', 202, '/eindopdracht/images/macintoshplus.png\r\n'),
(6, 'IBM ThinkPad 701', 'The IBM ThinkPad 701, often referred to as the \"butterfly\" ThinkPad, was a revolutionary laptop in terms of both design and functionality. Released in 1995, it was notable for its innovative \"butterfly\" keyboard, which expanded to a full-sized layout when opened. This unique design was achieved by using a spring-loaded mechanism that allowed the laptop to maintain a compact form factor when closed while still offering a comfortable typing experience when open. Powered by Intel\'s 486 processor, the ThinkPad 701 was a standout in the laptop market and quickly became a favorite for professionals who required portability and power. Its solid build quality, exceptional keyboard, and iconic design contributed to its success, and it remains a beloved device among retro tech enthusiasts.\r\n\r\n**Pre installed with Arch Linux.**', 78, '/eindopdracht/images/thinkpad701.png'),
(7, 'Power Macintosh G3', 'The Power Macintosh G3, introduced in 1997, was a critical moment in Apple\'s transition to PowerPC architecture. It was the first model to feature the PowerPC G3 processor, which offered a significant performance boost over the previous 680x0 series used in earlier Macintosh systems. The G3 was available in various configurations, including tower and all-in-one models, and it marked a major shift in design with its use of a more minimalist and streamlined case. The machine became popular among professionals in creative fields such as graphic design, video editing, and music production due to its increased processing power and its compatibility with Apple\'s growing range of professional software. The Power Macintosh G3 played a key role in Apple\'s resurgence during the late 1990s.', 299, '/eindopdracht/images/powermacintosh.png'),
(8, 'Sony Playstation 1G', 'Released in 1994, the Sony PlayStation revolutionized the gaming industry with its 3D graphics, extensive game library, and cutting-edge technology. It marked the beginning of Sony’s dominance in the console gaming market, challenging established players like Nintendo and Sega. Powered by a 33.8688 MHz MIPS processor, the PlayStation was capable of rendering 3D graphics at a time when many other consoles were still limited to 2D. This, combined with its CD-ROM-based games, allowed for larger, more immersive titles. The PlayStation\'s success was driven by iconic games like Final Fantasy VII, Gran Turismo, and Tekken, which showcased the console\'s graphical capabilities and helped define the gaming experience of the era.', 70, '/eindopdracht/images/playstation1g.png'),
(9, 'Newton MessagePad 100', 'The Apple Newton MessagePad 100, released in 1993, was one of the first Personal Digital Assistants (PDAs) and a precursor to modern-day smartphones and tablets. It featured a 7.5-inch monochrome touchscreen, which allowed users to navigate menus and even write handwritten notes. The Newton\'s handwriting recognition system, though ahead of its time, faced challenges but was notable for its ambition and innovative design. Powered by a 20 MHz ARM processor, it came with 4MB of RAM and could connect to computers via serial ports. Although the Newton didn’t find mainstream success and was discontinued in 1998, it remains a beloved collector\'s item for tech enthusiasts due to its historical significance and pioneering features.', 143, '/eindopdracht/images/newton.png'),
(10, 'Powerbook 100', 'The PowerBook 100, introduced by Apple in 1991, was one of the first truly portable Macintosh computers. With a compact form factor and a 9-inch black-and-white screen, the PowerBook 100 made computing on-the-go accessible to a wider audience. It featured a Motorola 68000 processor and came with 2MB of RAM, expandable to 8MB, with storage options ranging from a 40MB to 80MB hard drive. Notably, it was one of the first laptops to feature an integrated trackpad, which set the standard for future portable computing devices. Despite its limited performance by today’s standards, the PowerBook 100 was a pioneering model in the laptop market and laid the foundation for Apple’s successful portable computing lineup.', 169, '/eindopdracht/images/powerbook100.png'),
(11, 'Nintendo 64', 'Released in 1996, the Nintendo 64 was a groundbreaking gaming console that introduced 3D graphics to the gaming world, elevating the experience with titles like Super Mario 64 and The Legend of Zelda: Ocarina of Time. With its 64-bit architecture and custom-designed graphics chip, the N64 offered revolutionary gameplay and a more immersive gaming experience compared to previous consoles. The system\'s distinctive controller, with its three-pronged design, was ergonomically designed for 3D gameplay, and the console’s library included iconic games that defined a generation. Although the N64 faced tough competition from Sony’s PlayStation, it remains a beloved console for its innovative titles and its lasting impact on the gaming industry.', 52, '/eindopdracht/images/n64.png'),
(12, 'Toshiba T1200', 'The Toshiba T1200, released in 1985, was one of the earliest portable computers to feature an Intel 80286 processor. It offered a significant leap forward in computing portability compared to its contemporaries, weighing just 4.4kg and sporting a 9-inch monochrome screen. With 512KB of RAM and a 20MB hard drive, the T1200 was designed for business professionals who needed a portable solution. It ran MS-DOS and was compatible with a range of software designed for IBM PCs, making it a versatile option for its time. Although its design was more utilitarian than stylish, the Toshiba T1200 is remembered for its durability and importance in the development of portable computing.', 150, '/eindopdracht/images/toshibat1200.png'),
(14, 'Commodore 64', 'The Commodore 64, released in 1982, remains one of the best-selling personal computers of all time, with an estimated 12 to 17 million units sold. Known for its 8-bit processor and robust capabilities in gaming and home computing, the C64 featured a full-sized keyboard, 64KB of RAM, and the renowned SID sound chip, which made it a favorite for music and sound enthusiasts. The C64\'s library of software, including games, educational programs, and productivity tools, helped establish its widespread popularity. It also supported a range of peripherals like printers, disk drives, and modems. While the C64 eventually gave way to more advanced computing systems, it remains an iconic piece of computing history, fondly remembered for its versatility and affordability.', 88, '/eindopdracht/images/c64.png'),
(15, 'Ipod Nano 1G', 'The iPod Nano (1st Gen), released in 2005, was a significant step forward in Apple\'s iPod lineup, combining the sleek design of the iPod Mini with the more compact size and higher storage capacity. Featuring a 1.5-inch monochrome LCD display and a capacity of 1GB or 2GB, the iPod Nano quickly became one of the most popular portable music players due to its small form factor, ease of use, and affordability. The Nano was available in multiple colors, and despite its small size, it could hold hundreds of songs, making it a highly portable and practical solution for music lovers. This generation marked the beginning of the iPod Nano\'s long evolution, which would continue to innovate with new designs and features in the years that followed. The Nano\'s thin, durable construction and the simplicity of its click wheel interface made it a standout device in the iPod family.', 50, '/eindopdracht/images/nano1g.png'),
(16, 'HP Jornada 720', 'The HP Jornada 720, released in 2001, was one of the leading Windows CE-based handheld devices of its time. Featuring a 6.1-inch color touchscreen and a strong design, the Jornada 720 could handle both personal and business applications, from note-taking to email. Powered by a 206 MHz processor and featuring 32MB of RAM, it ran Windows CE and supported various software applications. The device’s ability to sync with Microsoft Outlook and its expansion options made it a popular choice for professionals who needed to stay connected on-the-go. Although it was ultimately overshadowed by the rise of more capable PDAs and smartphones, the HP Jornada 720 remains a collector’s item for those interested in the evolution of mobile computing.', 52, '/eindopdracht/images/jornada.png'),
(17, 'Palm Pilot 5000', 'The Palm Pilot 5000, released in 1996, helped establish Palm as one of the leaders in the PDA market. Featuring a monochrome touchscreen and a sleek, compact design, the Pilot 5000 was designed for professionals who needed a portable, easy-to-use tool for managing contacts, appointments, and notes. With 2MB of storage and the ability to sync with PCs via infrared, the Pilot 5000 was a highly functional device for its time. The Palm Pilot’s handwriting recognition system, Graffiti, made inputting data easier, and its ecosystem of third-party apps expanded its functionality. Although PDAs have been largely replaced by smartphones, the Palm Pilot 5000 remains an iconic part of early mobile computing history.', 32, '/eindopdracht/images/palmpilot.png'),
(18, 'Sony Walkman TPS-L2\r\n', 'The Sony Walkman TPS-L2, released in 1979, revolutionized personal music listening by making it portable for the first time. The first model in the Walkman series, it featured a cassette tape player, headphones, and a sleek, portable design that allowed users to listen to music anywhere. Powered by AA batteries, the TPS-L2 offered up to 10 hours of playback on a single charge, making it ideal for long trips or daily commuting. Its introduction marked the beginning of a cultural shift in how people interacted with music, as the Walkman became a symbol of freedom and mobility in the 1980s. Though the Walkman was originally designed for cassette tapes, the brand would go on to evolve with the times, eventually including CD players, mini-discs, and digital media players.\r\n\r\n', 178, '/eindopdracht/images/walkman.png'),
(19, 'Atari Jaguar', 'Released in 1993, the Atari Jaguar was one of the last major attempts to compete with the 16-bit and 32-bit console wars of the early \'90s. Despite its technical capabilities, which included a 64-bit architecture and impressive graphics performance, the Jaguar was marred by a limited game library and marketing challenges. The console\'s standout titles, such as Alien vs. Predator and Tempest 2000, showcased the system\'s potential, but it struggled to gain traction in a market dominated by the Sony PlayStation and Sega Saturn. The Atari Jaguar was ultimately discontinued in 1996, and it is now a rare collector\'s item. Its legacy remains mixed, but it still holds a niche place in retro gaming history.', 121, '/eindopdracht/images/atarijag.png');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `films`
--
ALTER TABLE `films`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `films`
--
ALTER TABLE `films`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=70;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
